
version: '3'
services: 

  unico-mysql:
    image: mysql:5.7
    container_name: unico_db_mysql
    expose: 
      - 3306
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - ENVINRONMENT=${ENVIRONMENT}      
    networks:
      - netunico
  


#  app:
#    container_name: unico_app
#    build: .
#    ports: 
#      - 8080:8080 
#    restart: on-failure
#    volumes:
#      - api:/app/
#    depends_on:
#      - unico-mysql    
#    networks:
#      - netunico
#    environment: 
#      - MYSQL_ROOT_HOST=${DB_HOST} 
#      - MYSQL_USER=${DB_USER}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=${DB_NAME}
#      - ENVINRONMENT=${ENVIRONMENT}


volumes:
#  api:

networks:
  netunico:
    driver: bridge